version: '3.1'

services:
  db:
    image: postgres-pgvector
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data